### ISSUE TITLE
Again in need adjustment according to the new website

### ISSUE THREAD

**Issue by mihaelmilea** [alefnode/mobile-whatsweb#6]
Whatsapp changed again its format so we can't access / view chats upon startup...

Again we are thanking you for taking the time to help with a new version of the app that would accommodate the changes.

Thank you!

**Comment by alefnode** [comment]
Working on it, almost done, i am testing new code

**Comment by panpanpanpaan** [comment]
Hey, i saw that you fixed this in ubports, is it possible to solve this in here as well?
